### ISSUE TITLE
Curly bracket in annote field

### ISSUE THREAD

**Issue by ferdinandeibl** [adamjgnoel/mendeleyBibFix#10]
Dear Adam, 

As requested, I'm creating the issue regarding the problem of curly brackets occuring in annote fields which trigger the script to stop scanning. A further problem, which may be more difficult to resolve, is when there is line breaks and curly brackets in the annote field (which is my case). 

Many thanks again for this amazing code. 

Ferdinand

**Comment by adamjgnoel** [comment]
Yes, an ending curly brace inside of an "annote" field will prematurely stop the scan to remove this field. A slightly better (but not foolproof) approach would be to search for "},\n", which is less likely to be confused elsewhere. The optimal solution would be to track the number of opened and closed curly braces, so that the scan is stopped once the closing curly brace that corresponds to the opening curly brace is detected (though this still isn't "perfect" because you might have added an extra closing curly brace somewhere).

**Comment by adamjgnoel** [comment]
I have updated the search for the end of an "annote" field to look for "},\n" instead of "},". This makes the search a bit more robust to custom text within the annotation field, but it will still remove the annotation incorrectly if there is "},\n" within the text of the annotation itself.
