### ISSUE TITLE
How can i remove DOI field

### ISSUE THREAD

**Issue by beebrain** [adamjgnoel/mendeleyBibFix#11]
Thank you for your script to fix bib from mendeley.
I have some problems with the DOI field. I use BibTeX to create the ref, but some article has an underscore in DOI field that make a problem. How can I remove the DOI field in the bib file?

**Comment by adamjgnoel** [comment]
The short answer is to directly modify the source code by copying the code for removing the URL (lines 325-333 in current source version) and in the copy change the argument "url =" in the call to strncmp to "doi =". Compiling this code should then successfully remove all DOIs.

However, I do note that the printing of DOIs would also depend on the options of your bibliography style. For example, by default DOIs are not included in bibliographies made using the IEEE style. I also note that if you are getting links made for your DOIs then there is probably a hyperlink option in your document that is creating these (e.g., the hyperref  package). The links won't work for the default Mendeley formatting of DOIs because of the missing "dx.doi.org/" at the start of every DOI.
