### ISSUE TITLE
June is abbreviated to Jun

### ISSUE THREAD

**Issue by SteCla** [adamjgnoel/mendeleyBibFix#2]
June should remain June according to:
http://guides.lib.monash.edu/c.php?g=219786&p=1454302

**Comment by adamjgnoel** [comment]
Yes, the IEEE standard specifies that June and July should be written in full.

The bib-file standard uses 3-letter months. This is independent of how the months are written in a bibliography, as that is governed by the style file. (Unfortunately), the IEEEtran style file converts all months to 3-letter format (see http://www.michaelshell.org/tex/ieeetran/bibtex/)

The original issue with how Mendeley writes the dates is that it places the lowercase 3-letter month inside of curly braces, which forces the output to be in that format (e.g., we get "jun" instead of "Jun."). One potential workaround is to identify {jun} and {jul} and replace them with {June} and {July} instead of jun and jul, respectively.

I have 2 reasons to not do this:

1. This workaround would be specific to IEEE formatting and may not be appropriate for other styles
2. This may be the IEEE standard, but it is rarely a problem in practice. As I already noted, the IEEEtran style converts all months to 3-letter format when they are entered normally. I can find many examples of IEEE papers that use "Jun." and "Jul." in their bibliographies. These cases may violate the standard, but not as egregiously as the other problems that this code addresses

**Comment by adamjgnoel** [comment]
Actually, this code also lets you hard-code the date in your desired format. If you remove the "year" and write the custom date in the "ISSN" field, then this script will replace the year with the ISSN. You could put, for example, "June 2017" in the ISSN and it should appear as such in the bibliography.

However, this is more work for the user than if the code just figured it out on its own.
